### ISSUE TITLE
error TS2740:  ????

### ISSUE THREAD

**Issue by BMeridian** [tflanagan/node-e-trade#5]
TSError: ⨯ Unable to compile TypeScript:
etradeApiTest.ts(152,9): error TS2740: Type 'CancelOrderResponse' is missing the following properties from type 'Account[]': length, pop, push, concat, and 28 more.

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:843:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:847:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:1057:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1411:41)
    at transformSource (/usr/local/lib/node_modules/ts-node/src/esm.ts:400:37)
    at /usr/local/lib/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/usr/local/lib/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:602:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:458:11) {
  diagnosticCodes: [ 2740 ]
}

this works:

let results = await eTrade.listAccounts();
console.log(results[2]);
// console.log(results[2].accountIdKey);
 const _accountIdKey = results[2].accountIdKey

**Comment by tflanagan** [comment]
Not sure I understand this.

The error references 'CancelOrderResponse', but also 'Account'?

Can you provide some more details?

**Comment by tflanagan** [comment]
I'm going to close this.

If you are still experiencing this issue, please reopen this, but can you provide some steps to reproduce this?
